// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxcscwdzefsxjwnwazwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4Y3Njd2R6ZWZzeGp3bndhendyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1OTc3MDMsImV4cCI6MjA3NjE3MzcwM30.PR5l2Hu7EC_GwfaJJ33jXc5d3lLH0GFEeMVq5Og4OyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});